#!/usr/bin/env bash
# snapshot.sh — gather repo state for session-context orient/checkpoint flows.
#
# Usage: bash snapshot.sh [<repo-dir>]
#   <repo-dir>  optional; defaults to the current working directory.
#
# Prints a ready-to-paste STATUS.md "Snapshot" section to stdout.
# Exits 0 always — individual sub-commands degrade gracefully when tools are
# absent (gh, git) rather than aborting the whole snapshot.
#
# MIT — part of sidequests/skills/session-context

REPO_DIR="${1:-$(pwd)}"

# ── helper: print a section header ───────────────────────────────────────────
section() { printf '\n### %s\n' "$1"; }

# ── header ───────────────────────────────────────────────────────────────────
printf '## Snapshot (auto)\n'
printf '<!-- generated by snapshot.sh on %s -->\n' "$(date -u '+%Y-%m-%dT%H:%MZ' 2>/dev/null || date)"
printf 'Repo: %s\n' "$REPO_DIR"

# ── verify git is available and this is a git repo ───────────────────────────
if ! command -v git >/dev/null 2>&1; then
  printf '\n(git not found — cannot gather repo state)\n'
  printf '\n---\n\n'
  exit 0
fi

if ! git -C "$REPO_DIR" rev-parse --git-dir >/dev/null 2>&1; then
  printf '\n(not a git repo: %s)\n' "$REPO_DIR"
  printf '\n---\n\n'
  exit 0
fi

# ── git branch ───────────────────────────────────────────────────────────────
section "Branch"
BRANCH=$(git -C "$REPO_DIR" branch --show-current 2>/dev/null)
if [ -z "$BRANCH" ]; then
  BRANCH=$(git -C "$REPO_DIR" rev-parse --abbrev-ref HEAD 2>/dev/null || printf '(detached HEAD)')
fi
printf '%s\n' "$BRANCH"

# ── recent commits ───────────────────────────────────────────────────────────
section "Recent commits (last 15)"
git -C "$REPO_DIR" log --oneline -15 2>/dev/null || printf '(no commits yet)\n'

# ── working-tree status ──────────────────────────────────────────────────────
section "Working-tree status"
STATUS=$(git -C "$REPO_DIR" status -s 2>/dev/null)
if [ -z "$STATUS" ]; then
  printf 'clean\n'
else
  printf '%s\n' "$STATUS"
fi

# ── open PRs (gh optional) ───────────────────────────────────────────────────
section "Open PRs"
if ! command -v gh >/dev/null 2>&1; then
  printf '(gh CLI not found — skipped)\n'
else
  # gh pr list needs to run inside the repo directory
  PR_OUTPUT=$(cd "$REPO_DIR" && gh pr list --state open 2>/dev/null)
  GH_EXIT=$?
  if [ $GH_EXIT -ne 0 ]; then
    printf '(gh pr list failed — not authenticated or no GitHub remote)\n'
  elif [ -z "$PR_OUTPUT" ]; then
    printf 'none\n'
  else
    printf '%s\n' "$PR_OUTPUT"
  fi
fi

printf '\n---\n\n'
